# "image-build" github actions 
name: "image-build-python-project"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Start Build Image!!!!"
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with: 
          context: ./app
          push: true
          tags: octop162/sample-app:latest

